# Generated by Django 6.0.4 on 2026-05-09 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0003_remove_borrowing_unique_active_borrowing_per_copy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address_source",
                    models.CharField(
                        choices=[("user", "Из профиля пользователя"), ("custom", "Введен вручную")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес доставки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("in_progress", "В пути"),
                            ("delivered", "Доставлено"),
                            ("canceled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус доставки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "borrowing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="borrowing.borrowing",
                        verbose_name="Выдача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
                "ordering": ["-created_at"],
            },
        ),
    ]
