# Generated by Django 6.0.4 on 2026-05-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, help_text="Расскажите о себе", verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Введите дату рождения", null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active_reader",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
