# Generated by Django 6.0.4 on 2026-05-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bio_user_date_of_birth_user_is_active_reader_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("admin", "Администратор"),
                    ("student", "Студент"),
                    ("active_reader", "Активный читатель"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
