# Generated by Django 6.0.4 on 2026-05-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="Введите имя", max_length=200, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Введите фамилию", max_length=200, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, help_text="Введите отчество", max_length=200, null=True, verbose_name="Отчество"
                    ),
                ),
                ("bio", models.TextField(help_text="Введите описание", verbose_name="Описание")),
                (
                    "years_of_life",
                    models.CharField(help_text="Введите годы жизни", max_length=50, verbose_name="Годы жизни"),
                ),
                (
                    "image",
                    models.ImageField(help_text="Добавьте фотографию", upload_to="authors/", verbose_name="Фото"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите жанр книги", max_length=100, unique=True, verbose_name="Жанр"),
                ),
                ("description", models.TextField(help_text="Введите описание", verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название книги", max_length=300, verbose_name="Название"),
                ),
                ("description", models.TextField(help_text="Введите описание", verbose_name="Описание")),
                (
                    "publish_date",
                    models.DateField(
                        blank=True, help_text="Введите дату публикации", null=True, verbose_name="Дата публикации"
                    ),
                ),
                ("cover", models.ImageField(upload_to="books/")),
                ("isbn", models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
                ("genres", models.ManyToManyField(related_name="books", to="books.genre", verbose_name="Жанры")),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["title"],
            },
        ),
    ]
