# Generated by Django 6.0.4 on 2026-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название библиотеки", max_length=300, verbose_name="Название"),
                ),
                (
                    "address",
                    models.CharField(help_text="Введите название библиотеки", max_length=300, verbose_name="Адрес"),
                ),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="Широта")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="Долгота")),
                ("description", models.TextField(blank=True, help_text="Введите описание", verbose_name="Описание")),
                ("image", models.ImageField(help_text="Добавьте фото", upload_to="libraries/", verbose_name="Фото")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Библиотека",
                "verbose_name_plural": "Библиотеки",
                "ordering": ["name"],
            },
        ),
    ]
