# Generated by Django 6.0.4 on 2026-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("borrowed_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(verbose_name="Дата возврата")),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("returned", "Возвращена"), ("overdue", "Просрочена")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача книги",
                "verbose_name_plural": "Выдача книг",
                "ordering": ["-borrowed_at"],
            },
        ),
    ]
