# Generated by Django 6.0.4 on 2026-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="unique_active_borrowing_per_copy",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrowed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата взятия"),
        ),
    ]
