# Generated by Django 6.0.4 on 2026-05-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inventory_number", models.CharField(max_length=50, verbose_name="Инвентарный номер")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступна"),
                            ("borrowed", "Выдана"),
                            ("lost", "Утеряна"),
                            ("damaged", "Повреждена"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_copies",
                        to="libraries.library",
                        verbose_name="Библиотека",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экземпляр книги",
                "verbose_name_plural": "Экземпляры книги",
                "ordering": ["book", "library"],
                "unique_together": {("library", "inventory_number")},
            },
        ),
    ]
